### ISSUE TITLE
Testing the new method reading 

### ISSUE THREAD

**Issue by mbabovic** [sgibb/topdownr#81]
I've recorded some myoglobin data with the new method, but I wasn't able to analyse it. ReadTopDownFiles stops on mergeScanConditionAndHeaderInformation.
The files I used are on the google drive (tell me if you didn't get the link)
I've included the output from scanheadsman and the PD processing method. I had to use PD 2.3 for deconvolution instead of 2.1 we were using before, but the PD workflow stayed the same

**Comment by pavel-shliaha** [comment]
@mbabovic could you please copy the error message here, so Sebastian can reproduce it?

**Comment by sgibb** [comment]
I got the error "The retention times from header and spectra files differ.". That is an internal check after merging the output of the combined experiment.csv+scanheadmans table with the mzML data. The order seems to differ agian: e.g. `PrecursorMz` in mzML: 893, 1211, 707

"File" | "Scan" | "RetentionTime" | "PrecursorMz" | "ScanDescription" | "RtMin" | "BasePeakPosition"
---|---|---|---|---|---|---
"2019_06_25_myoglobin_03" | 2 | 6.818634561 | 893.114013671875 | "C01" | 0.02864 | 707.29736
"2019_06_25_myoglobin_03" | 3 | 12.174438033 | 1211.71960449219 | "C01" | 0.11364 | 893.12103
"2019_06_25_myoglobin_03" | 4 | 17.788397089 | 707.258666992188 | "C01" | 0.20291 | 1211.64771
"2019_06_25_myoglobin_03" | 5 | 22.888312433 | 893.114013671875 | "C02" | 0.29647 | 707.29718
"2019_06_25_myoglobin_03" | 6 | 28.24462053 | 1211.71960449219 | "C02" | 0.38147 | 893.11908
"2019_06_25_myoglobin_03" | 7 | 33.857938097 | 707.258666992188 | "C02" | 0.47074 | 1211.71655
"2019_06_25_myoglobin_03" | 8 | 38.957860449 | 893.114013671875 | "C03" | 0.5643 | 707.29584
"2019_06_25_myoglobin_03" | 9 | 44.315190033 | 1211.71960449219 | "C03" | 0.6493 | 893.14807
"2019_06_25_myoglobin_03" | 10 | 49.928246928 | 707.258666992188 | "C03" | 0.73859 | 1211.7157
"2019_06_25_myoglobin_03" | 11 | 55.027914992 | 893.114013671875 | "C04" | 0.83214 | 707.29712
"2019_06_25_myoglobin_03" | 12 | 60.3844741930002 | 1211.71960449219 | "C04" | 0.91713 | 893.15375
"2019_06_25_myoglobin_03" | 13 | 65.9986738090002 | 707.258666992188 | "C04" | 1.00641 | 1211.71582

This happens because the first scan in `2019_06_25_myoglobin_03.txt` is MS level 1 and gets filtered. But there isn't any MS level 1 scan in  `2019_06_25_myoglobin_03.mzML`. So the second scanheadsman scan is mapped to the first mzml scan, the third to the second and so on.
Any reason why the mzML has no ms level 1 scans anymore?

**Comment by pavel-shliaha** [comment]
The deconvolution software is implemented in proteome discoverer and there might be a separate node that filters out MS1 scans, that I did not use before.

However, in general this check should be removed and mzML scans should be matched to the scanheadsman output explicitly (by scan number or retention time), since sometimes you can also loose MS2 scans if the deconvolution software does not identifiy any fragments. The deconvolution software will remove those scans rather than returning empty spectra.

In order to come up with the best solution I need access to the files. 

@mbabovic I did not get access to the new files. Could you please post the link to the files here.

**Comment by mbabovic** [comment]
I included the MS1 filter in the PD, because I've seen that MS1 scans are filtered from the scanheadsmen output, so I guessed there is no reason to have them in mzML. Should I stop using this filter?

This is the scanheadsman output without MS1:

Scan | MSOrder | FilterString | RT [min] | BasePeakPosition
-- | -- | -- | -- | --
2 | 2 | FTMS + p NSI Full ms2 707.3000@cid5.00 [350.0000-2000.0000] | 0.0286 | 707.3
3 | 2 | FTMS + p NSI Full ms2 893.1000@cid5.00 [350.0000-2000.0000] | 0.1136 | 893.12
4 | 2 | FTMS + p NSI Full ms2 1211.7000@cid5.00 [350.0000-2000.0000] | 0.2029 | 1211.6
5 | 2 | FTMS + p NSI Full ms2 707.3000@cid10.00 [350.0000-2000.0000] | 0.2965 | 707.3


And mzML:

Scan | MS level | Scan Time | Base Peak m/z | Precursor info
-- | -- | -- | -- | --
1 | 2 | 0.0286 | 5629.33838 | 707.25867
2 | 2 | 0.1136 | 16897.076 | 893.11401
3 | 2 | 0.2029 | 16895.9513 | 1211.7196
4 | 2 | 0.2965 | 5633.01258 | 707.25867

If I get this correctly, the issue is that the scans are now matched based on the scan number, so in this case the first MS2 gets scan number 2 in scanheadsman, and number 1 in mzML. Is there a reason not to match based on the retention time?

@pavel-shliaha Here are the files: https://drive.google.com/drive/folders/1Er1K6Ot9dQcFDXjsCxEDR52ZOr6BP3uU?usp=sharing

**Comment by sgibb** [comment]
> If I get this correctly, the issue is that the scans are now matched based on the scan number, so in this case the first MS2 gets scan number 2 in scanheadsman, and number 1 in mzML. 

Correct!

> Is there a reason not to match based on the retention time?

We didn't do this because the retention times differ slightly. Scanheadsman uses minutes and mzML seconds for the retention time. This leads to rounding errors, e.g. 0.02864 (scanheadsman) vs 0.028637206150 (mzML `1.718232369/60`). Using scan numbers was just simpler.

If necessary we could use a fuzzy/relaxed matching for the retention times to combine mzML and scanheadsman output (as we currently do for the matching control check that produce this error).

**Comment by pavel-shliaha** [comment]
I had a look at the files and there seems to be no reference to the original scan number in the XML file. I guess the only thing we could do is match based on RT? 

@ sebastian: could you just match to the closest  rt in scanheadsman? 

`
SH <- read.csv ("2019_06_25_myoglobin_03.txt")
mzMLSpec <- readMSData("2019_06_25_myoglobin_03.mzML")
sapply (SH$RT..min., function(x) which.min( abs (rtime (mzMLSpec)/60 - x ) ))
`

**Comment by sgibb** [comment]
Ok, should be fixed. Can you try, please?:
```r
devtools::install_github("sgibb/topdownr@newConditions")
library("topdownr")
tds <- readTopDownFiles("new_condition_labeling", conditions="ScanDescription")
```

**Comment by mbabovic** [comment]
Sorry for a very late reply, I just came back from vacation. 
Data loading now works fine. Thank you!
There is still an issue with high injection times, but we will have to solve that with Thermo

**Comment by sgibb** [comment]
Ok, so I am going to move this feature to bioconductor. Should `conditions="ScanDescription" be the new default argument?

**Comment by sgibb** [comment]
@mbabovic , @pavel-shliaha `conditions="FilterString"` is still the default option in `readTopDownFiles`. IMHO we should change this to `conditions="ScanDescription"` because that's the way the new xml files are generated. What is your opinion on that?

**Comment by sgibb** [comment]
/remind me to make `conditions="ScanDescription"` the new default on 1. December 2019

**Comment by mbabovic** [comment]
@sgibb I agree, it makes more sense to change it

**Comment by pavel-shliaha** [comment]
yes it makes much more sense. Please change it

**Comment by sgibb** [comment]
Thx @mbabovic and @pavel-shliaha . I changed the default and uploaded the new version (1.9.2) to Bioconductor.
